[package]
name = "craes"
version = "0.0.1"
authors = ["Nym Seddon <unseddd@shh.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
